### ISSUE TITLE
Not working for Chrome v45 Canary

### ISSUE THREAD

**Issue by ferrao** [alex-vv/chrome-load-timer#10]
It used to work last week, but It stopped working this week, I'm on v45 Canary, this is the error i got:

<pre>Uncaught TypeError: Illegal invocation

   Save.stringify @ extensions::SafeBuiltins:82 
   PortImpl.postMessage @ VM675 extensions::messaging:53
   target.(anonymous function) @ extensions::SafeBuiltins:19
   $Array.forEach.publicClass.(anonymous function) @ VM673 extensions::utils:94
   sendMessageImpl @ VM675 extensions::messaging:314
   (anonymous function) @ VM665 extensions::runtime:116
   target.(anonymous function) @    extensions::SafeBuiltins:19
   (anonymous function) @ VM666 extensions::binding:57
   target.(anonymous function) @ extensions::SafeBuiltins:19
   (anonymous function) @ VM666 extensions::binding:385
   (anonymous function) @ timer.js:24
</pre>

**Comment by Lock128** [comment]
Yep, I m having the same problem.

**Comment by plefr** [comment]
Me too. I'm using Chrome Dev channel 45.

**Comment by lucianmarin** [comment]
Same issue with Chrome 44 beta (64-bit).

**Comment by alex-vv** [comment]
Fixed in 1.2.4

**Comment by Lock128** [comment]
Fixed for me, thanks a lot.
