### ISSUE TITLE
Possible pull request(s)

### ISSUE THREAD

**Issue by nijk** [alex-vv/chrome-load-timer#12]
I was very impressed with this load timer, as such I decided to fork it and see if I could add some improved UI & further features to the repo. The [result is here](https://github.com/nijk/chrome-load-timer). 

If you're interested or like anything you see on here then I'd be happy to raise a pull request(s) for anything you see on my forked version.

**Comment by alex-vv** [comment]
Thanks, I tried to check your version but unfortunately it doesn't fully works for me. Popup is not updated and shows `TypeError: results.forEach is not a function` at Object.Query (chrome-extension://nkcicobdkffhppfladajhljofbcogfmp/dman.js:50:17) in Inspect Popup. 
Using Chrome 49. 

Also I have some concerns regarding the source code. Not sure I like heavy manual DOM manipulations there. Have you tried to do client-side templating approach as stated in your updated README? I am not against some lightweight template lib dependency and if you can make code simpler I can consider merging.

**Comment by nijk** [comment]
Hi Alex,

Thanks for your feedback. I can't seem to replicate the issue you are describing which is strange as I'm also using Chrome 49. I've replaced that loop with a simple `for`, hopefully that will resolve your issue so that you can take a look at the popup UI changes.

With regards to your concerns about the DOM manipulation approach, I completely understand your point and as you've found in the README it is also a concern I have about the readability & maintainability of the DOM manipulation code. I will take a look into the templating lib options, the last time I looked I struggled to find one that was lightweight - so any suggestions here would be appreciated.

**Comment by alex-vv** [comment]
I updated popup to Material Design in https://github.com/alex-vv/chrome-load-timer/commit/9eb8b4d59b4c355f8366b65be17efa4fe16fd5d5 so I think this is no longer relevant
