### ISSUE TITLE
page load time does not account for chrome extension that may interact with the page loading

### ISSUE THREAD

**Issue by Jimbazuka** [alex-vv/chrome-load-timer#16]
Many users have 1 or more chrome browser extensions that by definition slow down the page loading. Hence page load time is a sum total of the page load time plus all interactions by various extensions (possibly including this "chrome load timer" extension ??). A more detailed analysis would prove beneficial to many users. This is not a bug per se, more of a improvement suggestion. A workaround is to disable all extensions, measure page load time, enable 1st extension, measure page load time, enable next extension, measure load time, ....repeat. However, with many extensions this is very tedious.

**Comment by alex-vv** [comment]
I'm afraid it is not possible to do in this extension because chrome doesn't allow to control other extensions. But can you give an example of extension which noticeably slows down some web page so I could check in more detail?
