### ISSUE TITLE
Please support Firefox

### ISSUE THREAD

**Issue by andreicristianpetcu** [alex-vv/chrome-load-timer#20]
Hi! Do you have any plans to support Firefox? Firefox extensions have the same format as Chrome extensions these days. https://vimeo.com/241435808 There are a few different APIs but they are mostly the same https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

**Comment by alex-vv** [comment]
yes, I am planning to take a look on that

**Comment by andreicristianpetcu** [comment]
Thank you!

**Comment by alex-vv** [comment]
I implemented Firefox support and I am planning to release it in the next version with other fixes and improvements.
