### ISSUE TITLE
Consider tightening permissions

### ISSUE THREAD

**Issue by Janpot** [alex-vv/chrome-load-timer#22]
As far as I understand, this extension would be able to do its job with just the [activeTab](https://developer.chrome.com/extensions/activeTab) permission. Provided there would be some sort of "activation step". It would offer more peace of mind to users though to have more control over when and where the extension can execute code.

**Comment by alex-vv** [comment]
Thanks for the suggestion! It indeed seems to be working fine with `activeTab` permission.

**Comment by alex-vv** [comment]
I fixed it but will release it later with other planned changes
