### ISSUE TITLE
Feature Request: Display performance.timing.requestStart

### ISSUE THREAD

**Issue by JamoCA** [alex-vv/chrome-load-timer#24]
I've searched for a Google Chrome extension that could identify the local date & time that a webpage was initially loaded.  While it's nice to know that it took Xms to load, when I have a lot of tabs open, I have no way of knowing whether that webpage was last requested/loaded within 1 minute, 1 hour or 1 day.

I edited the local version of this extension and added this to performance.js startCollect() function:

    l.pageRequestStart = performance.timing.requestStart;

This div is added to popup.html template (right below H3):

    <div id="requestStart"></div>

This is added to popup.js getSelectedTab() function to add the date string to the pop-up:

    document.getElementById("requestStart").innerHTML = new Date(t.pageRequestStart).toString();

... and this is what it looks like with the date/time string added.  (Again, I believe that this would be the first performance Chrome extension to display the request date if added to the master.)

![chromeloadtimer_20190227](https://user-images.githubusercontent.com/1112671/53522214-c49e8180-3a8e-11e9-89e6-f44ee218705e.png)

**Comment by alex-vv** [comment]
Thanks for the suggestion, I will implement this for the new version.
