### ISSUE TITLE
Is there a way to record page load times across sites?

### ISSUE THREAD

**Issue by connerxyz** [alex-vv/chrome-load-timer#26]
I'd like to be able participate in a browsing session (multiple tabs/windows requesting multiple sites over let's say 30 minutes) – and then see the loading data for that session.

Does chrome-load-timer support this? Is there some other way? 

Thanks.

**Comment by alex-vv** [comment]
No, sorry, this extension doesn't support this kind of task. I don't think it would be possible to implement this without a full rewrite, so it would be easier to create a new extension in that case. Maybe there is some other extension which does it the way you want, but I am not aware.

**Comment by JamoCA** [comment]
Hey @connerxyz Consider using Fiddler.  It will log absolutely everything.
https://www.telerik.com/fiddler

**Comment by connerxyz** [comment]
@JamoCA hey, fiddler looks awesome thanks!
